name = "claude-relay-worker"
workers_dev = true
compatibility_date = "2025-07-23"
main = "src/index.js"

# 请替换为你的 Cloudflare 账户 ID
# 在 Cloudflare Dashboard 右侧边栏可以找到
account_id = "1ace686be8b4c742bd9c4d0b59646fc8"

[[kv_namespaces]]
binding = "CLAUDE_KV"
# 请替换为你的 KV 命名空间 ID
# 在 Workers & Pages → KV 中创建命名空间后获取
id = "claude-relay-worker"

[triggers]
crons = ["0 */6 * * *"]

[observability.logs]
enabled = true
